name: sensor_pipeline
version: "1.0.0"
config-version: 2

profile: timeseries_etl

model-paths:
  - models

analysis-paths:
  - analysis

test-paths:
  - tests

seed-paths:
  - seeds

macro-paths:
  - macros

snapshot-paths:
  - snapshots

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  sensor_pipeline:
    +materialized: table

    staging:
      +schema: staging
      +materialized: table

    marts:
      +schema: staging
      +materialized: table

vars:
  data_folder: C:\Users\matte\Desktop\NPlus\01.Commesse\Soglie_A4\data\Adige_Ovest
  start_date: "2025-03-01"
  end_date: "2026-03-01"
